FROM httpd:2.4

# Enable necessary modules
RUN sed -i \
    -e 's/^#\(LoadModule .*mod_proxy.so\)/\1/' \
    -e 's/^#\(LoadModule .*mod_proxy_http.so\)/\1/' \
    -e 's/^#\(LoadModule .*mod_proxy_wstunnel.so\)/\1/' \
    -e 's/^#\(LoadModule .*mod_rewrite.so\)/\1/' \
    conf/httpd.conf

# Include our custom configuration
RUN echo "Include conf/extra/httpd-vhosts.conf" \
    >> conf/httpd.conf